### PR TITLE
Add option to specify median or mean instead of minimum time

### PR DESCRIPTION
**Pull request by chriselrod**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
> summarystat = median

@chriselrod is this a typo? Did you mean minimum?

**Comment by chriselrod** [comment]
Yes, it should say minimum. I briefly considered making median the default because I think there should be some penalty for noise. But changing it may be considered breaking. And most users would expect the minimum to be the default, so I figured it's probably the better choice anyway.

I'll probably make another PR where I just record minimum, median, mean, and maximum, adding each to the benchmark_result. Then the `plot` function will let you choose which.

**Comment by chriselrod** [comment]
Let's hold off on making a release until I do that. Removing an argument is technically breaking.

**Comment by DilumAluthge** [comment]
Whooops I almost registered 😬 luckily I caught it in time 😂 

https://github.com/JuliaRegistries/General/pull/28820

**Comment by chriselrod** [comment]
Ha, that was close!

**Comment by DilumAluthge** [comment]
Good thing we don't instant merge.

**Comment by DilumAluthge** [comment]
FWIW, if it had been merged, we could have just yanked that version, so it wouldn't have been the end of the world. But better to not have merged in the first place 😉

**Pull request merged**
